FROM python:3.12.3-alpine
WORKDIR /app
COPY . /app/

ARG INTERNAL_GATEWAY
ENV INTERNAL_GATEWAY=$INTERNAL_GATEWAY
ARG EXTERNAL_GATEWAY
ENV EXTERNAL_GATEWAY=$EXTERNAL_GATEWAY
ARG PING_COUNT
ENV PING_COUNT=$PING_COUNT
ARG INTERFACE_LAN
ENV INTERFACE_LAN=$INTERFACE_LAN
ARG INTERFACE_WIFI
ENV INTERFACE_WIFI=$INTERFACE_WIFI
ARG WIFI_SSID
ENV WIFI_SSID=$WIFI_SSID
ARG WIFI_BAND
ENV WIFI_BAND=$WIFI_BAND
ARG WIFI_PASSWORD
ENV WIFI_PASSWORD=$WIFI_PASSWORD

RUN apk add --no-cache gcc python3-dev musl-dev linux-headers
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

EXPOSE 4000
CMD ["python", "main.py"]
