global:  
  scrape_interval: 60s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wsn-ping'
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      - targets:
        - 10.147.20.184:4000
    metrics_path: /metrics/ping/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ocs-probe-network:4000 

  - job_name: 'wsn-speedtest'
    scrape_interval: 300s
    scrape_timeout: 60s
    static_configs:
      - targets:
        - 10.147.20.184:4000
    metrics_path: /metrics/speedtest/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ocs-probe-network:4000 

  - job_name: 'wsn-network'
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      - targets:
        - 10.147.20.184:4000
    metrics_path: /metrics/network/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ocs-probe-network:4000 

  - job_name: 'wsn-general'
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      - targets:
        - 10.147.20.184:4000
    metrics_path: /metrics/general/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ocs-probe-network:4000 

  - job_name: 'wsn-map'
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      - targets:
        - 10.147.20.184:4000
    metrics_path: /metrics/map/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ocs-probe-network:4000 